device_name = "Hello device"
#add display name to this, to be displayed on frontend

[capability."Turn Off"]
    available = true

[capability."Turn On"]
    available = true

[capability."blabla"]
    available = true

[capability."bla"]
    available = true
