use rsa::RsaPublicKey;
use std::time::Duration;
use tokio::time::sleep;

use self::client_registration_service::{Capability, RegistrationRequest};
use crate::client_connection;
use crate::client_registration::client_registration_service::registration_service_client::RegistrationServiceClient;
use crate::client_types::types;
use crate::SERVER_IP;
use types::Capabilities;

mod client_registration_service {
    tonic::include_proto!("iot.registration");
}

///Registers client with server, returns ID generated by server
//TODO: take in static array of Capability
pub async fn register_self(
    public_key: &RsaPublicKey,
) -> anyhow::Result<client_connection::ServerConnection> {
    let mut client = RegistrationServiceClient::connect(SERVER_IP).await?;
    let stringified_public_key: String = serde_json::to_string(public_key).unwrap();
    let response = client
        .register(RegistrationRequest {
            public_key: stringified_public_key,
            capabilities: vec![
                Capability {
                    available: true,
                    capability: Capabilities::TurnOn as i32,
                },
                Capability {
                    available: true,
                    capability: Capabilities::TurnOff as i32,
                },
            ],
        })
        .await?;

    let response = response.into_inner();
    let server_public_key = serde_json::from_str(&response.public_key).unwrap();

    println!("{}", response.certificate);
    return Ok(client_connection::ServerConnection::new(
        response.client_id,
        server_public_key,
        response.certificate,
    ));
}

///Repeats the register_self operation until success
pub async fn repeated_register_self(
    public_key: &RsaPublicKey,
) -> client_connection::ServerConnection {
    let id = loop {
        let id_req_result = register_self(public_key).await;
        match id_req_result {
            Ok(r) => {
                break r;
            }
            Err(ref e) => {
                eprintln!("Error During ID request, trying again");
                eprintln!("{}", e.to_string());
                sleep(Duration::from_millis(500)).await;
            }
        }
    };

    return id;
}
